ckpt_root: ckpt
device: 'cuda:0'
log: True
resume_iteration: True

dataset:
    name: CorruptMP3dDepthDataset
    common_kwargs:
        sequence_length: 327680 
    train_kwargs:
        scene_txt: data/matterport3d/scenes_train.txt
        rand_rotate: True
        rand_flip: True
        rand_gamma: True
    valid_kwargs:
        scene_txt: data/matterport3d/mp3d_scenes_test.txt
        rand_rotate: False
        rand_flip: False
        rand_gamma: False

training:
    epoches: 200
    iteration: 10
    batch_size: 8
    learning_rate: 1e-3
    learning_rate_decay_steps: 1000
    learning_rate_decay_rate: 0.98
    clip_gradient_norm: 3
    refresh: False

model:
    file: model.UNet_CFP
    modelclass: UNet_CFP
    VAT: False
    reconstruction: True
    kwargs:
      XI: 1e-6
      VAT_start: 0
      n_heads: 4
      alpha: 1 